profile::dbbackups::check::backups:
  s1:
    dump:
    - eqiad
    - codfw
    snapshot:
    - eqiad
    - codfw
  s2:
    dump:
    - eqiad
    - codfw
    snapshot:
    - eqiad
    - codfw
  s3:
    dump:
    - eqiad
    - codfw
    snapshot:
    - eqiad
    - codfw
  s4:
    dump:
    - eqiad
    - codfw
    snapshot:
    - eqiad
    - codfw
  s5:
    dump:
    - eqiad
    - codfw
    snapshot:
    - eqiad
    - codfw
  s6:
    dump:
    - eqiad
    - codfw
    snapshot:
    - eqiad
    - codfw
  s7:
    dump:
    - eqiad
    - codfw
    snapshot:
    - eqiad
    - codfw
  s8:
    dump:
    - eqiad
    - codfw
    snapshot:
    - eqiad
    - codfw
  x1:
    dump:
    - eqiad
    - codfw
    snapshot:
    - eqiad
    - codfw
  es4:
    dump:
    - eqiad
    - codfw
  es5:
    dump:
    - eqiad
    - codfw
  m1:
    dump:
    - eqiad
    - codfw
  m2:
    dump:
    - eqiad
    - codfw
  m3:
    dump:
    - eqiad
    - codfw
  m5:
    dump:
    - eqiad
    - codfw
  zarcillo:
    dump:
    - eqiad
    - codfw
  matomo:
    dump:
    - eqiad
  analytics_meta:
    dump:
    - eqiad
profile::dbbackups::check::freshness:
  dump: 691200
  snapshot: 259200